# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: StatisticsService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'StatisticsService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17StatisticsService.proto\x12\x11StatisticsService\"\x07\n\x05\x45mpty\"\x1d\n\rStringMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"3\n\x0bMeanRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\".\n\x06Sensor\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t2\xa5\x01\n\x11StatisticsService\x12\x43\n\ngetSensors\x12\x18.StatisticsService.Empty\x1a\x19.StatisticsService.Sensor0\x01\x12K\n\x07getMean\x12\x1e.StatisticsService.MeanRequest\x1a .StatisticsService.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StatisticsService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=46
  _globals['_EMPTY']._serialized_end=53
  _globals['_STRINGMESSAGE']._serialized_start=55
  _globals['_STRINGMESSAGE']._serialized_end=84
  _globals['_MEANREQUEST']._serialized_start=86
  _globals['_MEANREQUEST']._serialized_end=137
  _globals['_SENSOR']._serialized_start=139
  _globals['_SENSOR']._serialized_end=185
  _globals['_STATISTICSSERVICE']._serialized_start=188
  _globals['_STATISTICSSERVICE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
